version: 2.1

orbs:
   slack: circleci/slack@3.4.2

jobs:
  test:
    working_directory: ~/ci
    docker:
      - image: district0x/cljs-dev:85d4876
      - image: ipfs/go-ipfs:v0.5.1
        command: ["daemon", "--migrate=true", "--enable-pubsub-experiment"]
    steps:
      - checkout
      - restore_cache:
          name: Restore npm package cache
          keys:
            - npm-packages-{{ checksum "yarn-lock.json" }}
      - run:
          name: Install node modules
          command: yarn deps
      - save_cache:
          name: Save npm package cache
          key: npm-packages-{{ checksum "yarn-lock.json" }}
          paths:
            - ./node_modules/
      - run:
          command:
            yarn tests:once
      - slack/status:
          channel: travis-ci
          mentions: $CIRCLE_USERNAME

  deploy:
   machine: true
   steps:
     - checkout
     - run:
         name: Deploy to clojars
         command: lein release :patch
     - slack/status:
         channel: travis-ci
         mentions: $CIRCLE_USERNAME

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          context: district0x
      - approve_deploy:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: master
      - slack/approval-notification:
          context: district0x
          message: Pending approval
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          context: district0x
          requires:
            - approve_deploy
