version: 2.1

orbs:
   slack: circleci/slack@3.4.2
   node: circleci/node@1.1.6

# TODO : lint

jobs:
  test:
    working_directory: ~/ci
    docker:
      - image: circleci/clojure:openjdk-11-node
      - image: ipfs/go-ipfs:v0.5.1
        command: ["daemon", "--migrate=true", "--enable-pubsub-experiment"]
    environment:
      NODE_VERSION: 12.16.1
      YARN_VERSION: 1.22.1
    steps:
      - checkout
      - node/install:
          node-version: $NODE_VERSION
          yarn-version: $YARN_VERSION
      - node/with-cache:
          dir: ./node_modules/
          cache-version: yarn-packages-cljs
          cache-key: yarn.lock
          steps:
            - run: yarn deps
      - run: yarn lint
      - run:
          command:
            yarn tests:once
      - slack/status:
          channel: travis-ci
          mentions: $CIRCLE_USERNAME

  deploy:
   machine: true
   steps:
     - checkout
     - run:
         name: Deploy to clojars
         command: lein release :patch
     - slack/status:
         channel: travis-ci
         mentions: $CIRCLE_USERNAME

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          context: district0x
      - approve_deploy:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: master
      - slack/approval-notification:
          context: district0x
          message: Pending approval
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          context: district0x
          requires:
            - approve_deploy
